DB_NAME = 'hack'
QUESTION_MASTER_COLLECTION_NAME = 'questionMaster'
INSURER = 'insurer'
ANSWER_MASTER_COLLECTION_NAME = 'answerMaster'
AUDIO_TRANSCRIPPT_COLLECTION_NAME = 'transcript'
MONGO_URL = 'mongodb://localhost:27017/'
